#HADOOP_HOME=/path/to/your/hadoop/home
#SPARK_HOME=/path/to/your/spark/home
SCALA_HOME=scala/scala-2.11.8
HADOOP_VERSION=2.8.1
MY_CLASSPATH=${HADOOP_HOME}/share/hadoop/common/hadoop-common-${HADOOP_VERSION}.jar:${SPARK_HOME}/jars/*:${HADOOP_HOME}/share/hadoop/mapreduce/*:out:.
PROJECT_BASE=src/main/scala
INPUT_FOLDER=input
OUTPUT_FOLDER=output
JAR_NAME= "enter jar name here"///
MAIN_CLASS=millionSong

all: compile setup run

compile:
	${SCALA_HOME}/bin/scalac -cp ${MY_CLASSPATH} -d ${JAR_NAME} ${PROJECT_BASE}/*.scala

run:
	${SPARK_HOME}/bin/spark-submit --class ${MAIN_CLASS} ${JAR_NAME}

clean:
	$(HADOOP_HOME)/bin/hdfs dfs -rm -r output;

setup:
	$(HADOOP_HOME)/bin/hdfs dfs -rm -r -f ${INPUT_FOLDER}
	$(HADOOP_HOME)/bin/hdfs dfs -rm -r -f ${OUTPUT_FOLDER}
	rm -rf ${OUTPUT_FOLDER}
	$(HADOOP_HOME)/bin/hdfs dfs -mkdir ${INPUT_FOLDER}
	$(HADOOP_HOME)/bin/hdfs dfs -put ${INPUT_FOLDER}/* ${INPUT_FOLDER}

gzip:
	gzip ${INPUT_FOLDER}/${INPUT_TYPE}/*

gunzip:
	gunzip ${INPUT_FOLDER}/${INPUT_TYPE}/*


